
export const placeTypes = [
  "art_gallery",
  "bar",
  "cafe",
  "movie_theater",
  "museum",
  "night_club",
  "park",
  "restaurant",
  "shopping_mall",
  "stadium",
  "zoo",
  "airport",
  "aquarium",
  "atm",
  "bowling_alley",
  "bus_station",
  "car_rental",
  "casino",
  "city_hall",
  "convenience_store",
  "department_store",
  "embassy",
  "gas_station",
  "gym",
  "hair_care",
  "library",
  "liquor_store",
  "lodging",
  "spa",
  "supermarket",
  "transit_station",
];

export const placeTypesName = {
  amusement_park : "amusement_park",
	art_gallery : "Art Gallery",
	bar : "Bar",
	cafe : "Cafe",
	movie_theater : "Movie Theater",
	museum : "Museum",
	night_club : "Night Club",
	park : "Park",
	restaurant : "Restaurant",
	shopping_mall : "Shopping Mall",
	stadium : "Stadium",
	zoo : "Zoo",
	airport : "Airport",
	aquarium : "Aquarium",
	atm : "Atm",
	bowling_alley : "Bowling Alley",
	bus_station : "Bus Station",
	car_rental : "car Rental",
	casino : "Casino",
	city_hall : "City Hall",
	convenience_store : "Convenience Store",
	department_store : "Department Store",
	embassy : "Embassy",
	gas_station : "Gas Station",
	gym : "Gym",
	hair_care : "Hair Care",
	library : "Library",
	liquor_store : "Liquor Store",
	lodging : "Lodging",
	spa : "Spa",
	supermarket : "Supermarket",
	transit_station : "Transit Station",
}